### ISSUE TITLE
About Script.cs file

### ISSUE THREAD

**Issue by MakiseSatsuki** [crskycode/GSIWin_Script_Tool#1]
Please forgive me for my poor English.
When I use it to export 河原崎家の一族2  string from one of the .mes .
it throw Exception.
Here's a piece of hexadecimal code
00 00 00 36 0F 0A 89 A1 97 F6 95 E7 82 CE 82 A9
82 E8 82 B7 82 E9 8D C5 92 E1 82 C8 96 EC 98 59
82 DF 81 42 00 1B 00 1B 00 32 00 00 00 45 05 32
in Script.cs file case 0x1B read 4byte and then it will read 0x45 and throw Exception
if case 0x1B read 1byte it will be ok.

**Comment by crskycode** [comment]
There are many versions of GSIWin engine, they have some differences, this tool cannot read all of them. And you know, MES file don't have any version identifiers. If you want to make it work, fork this repo. :)

**Comment by MakiseSatsuki** [comment]
I understand.Thank you!
